services:
  - type: web
    name: 3d-configurator-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://pratikkanojiya:Ph9819740701@cluster0.fveoutd.mongodb.net/laundrydb?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://frontendwestern.netlify.app
      - key: SENDGRID_API_KEY
        value: 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
      - key: EMAIL_FROM
        value: "3D Configurator <pratikkanojiya9324@gmail.com>"
      - key: REPLY_TO
        value: pratikkanojiya9324@gmail.com