services:
  - type: web
    name: 3d-configurator-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://frontendwestern.netlify.app
      - key: SENDGRID_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: "3D Configurator <pratikkanojiya9324@gmail.com>"
      - key: REPLY_TO
        value: pratikkanojiya9324@gmail.com